#!/bin/bash

echo "🔐 Firebase Service Account Setup"
echo ""
echo "To add your Firebase service account key:"
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo "2. Select your project: erkumardevender"
echo "3. Go to Project Settings → Service Accounts"
echo "4. Click 'Generate New Private Key'"
echo "5. Download the JSON file"
echo ""
echo "Then run this command (replace PATH_TO_JSON with your file path):"
echo ""
echo "  cat PATH_TO_JSON | jq -c . | sed \"s/'/\\\\'/g\" | xargs -I {} echo \"FIREBASE_SERVICE_ACCOUNT_KEY='{}'\" >> .env.local"
echo ""
echo "Or manually:"
echo "1. Open the downloaded JSON file"
echo "2. Copy the entire content"
echo "3. Add this line to .env.local:"
echo "   FIREBASE_SERVICE_ACCOUNT_KEY='<paste-json-content-here>'"
echo ""
echo "⚠️  Make sure the JSON is on a single line and properly escaped!"
echo ""

